// <auto-generated />
using System;
using AmiiboRewards.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmiiboRewards.Infrastructure.Migrations
{
    [DbContext(typeof(AmiiboRewardsDbContext))]
    [Migration("20260922194213_ReconcileNormalizedInteractionModel")]
    partial class ReconcileNormalizedInteractionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmiiboRewards.Domain.Amiibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalTableId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MappingSource")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MappingStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "InternalTableId")
                        .IsUnique();

                    b.ToTable("Amiibo");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.AmiiboReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmiiboId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<string>("DropSourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DropSourceSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntryIndex")
                        .HasColumnType("integer");

                    b.Property<string>("InteractionKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<int?>("MinCount")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Probability")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("RawWeight")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecialMetadata")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("AmiiboId", "RewardId", "Pool", "EntryIndex")
                        .IsUnique();

                    b.ToTable("AmiiboRewards");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "InternalId", "AssetType")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastDetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RomFsPath")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Kind", "SourceSha256")
                        .IsUnique();

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionSourcePath")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionSourceSha256")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IconAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameSourcePath")
                        .HasColumnType("text");

                    b.Property<string>("NameSourceSha256")
                        .HasColumnType("text");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IconAssetId");

                    b.HasIndex("GameId", "InternalId")
                        .IsUnique();

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.RewardLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RewardId", "Locale")
                        .IsUnique();

                    b.ToTable("RewardLocalizations");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Amiibo", b =>
                {
                    b.HasOne("AmiiboRewards.Domain.Game", "Game")
                        .WithMany("Amiibo")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.AmiiboReward", b =>
                {
                    b.HasOne("AmiiboRewards.Domain.Amiibo", "Amiibo")
                        .WithMany("Rewards")
                        .HasForeignKey("AmiiboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmiiboRewards.Domain.Reward", "Reward")
                        .WithMany("AmiiboRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amiibo");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Asset", b =>
                {
                    b.HasOne("AmiiboRewards.Domain.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.ImportRun", b =>
                {
                    b.HasOne("AmiiboRewards.Domain.Game", "Game")
                        .WithMany("ImportRuns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Reward", b =>
                {
                    b.HasOne("AmiiboRewards.Domain.Game", "Game")
                        .WithMany("Rewards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmiiboRewards.Domain.Asset", "IconAsset")
                        .WithMany()
                        .HasForeignKey("IconAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("IconAsset");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.RewardLocalization", b =>
                {
                    b.HasOne("AmiiboRewards.Domain.Reward", "Reward")
                        .WithMany("Localizations")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Amiibo", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Game", b =>
                {
                    b.Navigation("Amiibo");

                    b.Navigation("ImportRuns");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("AmiiboRewards.Domain.Reward", b =>
                {
                    b.Navigation("AmiiboRewards");

                    b.Navigation("Localizations");
                });
#pragma warning restore 612, 618
        }
    }
}
